version: '3'

services:
  lan-party:
    image: nouko61/usbeam-lan-party
    restart: always
    ports:
      - "3075:3075/tcp"
      - "3074:3074/udp"
    volumes:
      - "./lan-party:/lan-party/data"
    cap_add:
      - NET_ADMIN
